# name: Python CI Workflow

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.9
#     - name: Install dependencies
#       run: |
#         pip install -r requirements.txt
#     - name: Run tests
#       run: |
#         python -m unittest discover


name: Python CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Step 4: Run tests
    - name: Run tests
      run: |
        python -m unittest discover

    # Step 5: Create deployment artifact
    - name: Create artifact
      run: |
        zip -r app.zip .

    # Step 6: Upload to S3
    - name: Upload artifact to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "us-east-2"
      run: |
        aws s3 cp app.zip s3://my-app-artifacts/app.zip
        # Step 7: Deploy to Elastic Beanstalk
        
    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "us-east-2"
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name "devops" \
          --version-label "v1.0" \
          --source-bundle S3Bucket="my-app-artifacts",S3Key="app.zip"
        aws elasticbeanstalk update-environment \
          --application-name "devops" \
          --environment-name "devops-env" \
          --version-label "v1.0"



